#!/usr/bin/env ruby

require 'sequel'
require 'sqlite3'

DB = Sequel.connect('sqlite://rcdash.db')

DB.create_table :users do
  primary_key :id
  String :mac
  String :email
  String :zulip_id
  String :name
  DateTime :last_seen
end