#!/usr/bin/env ruby

require 'json'
require 'net/http'

loop do
  `tshark -Tfields -e eth.addr -a duration:15 > capture.tmp`
  `uniq capture.tmp > uniqcapture.tmp`

  uniq_capture = File.read("uniqcapture.tmp").split("\n")

  uniq_macs = uniq_capture.map { |line| line.split(",").last }

  payload = {"seen" => uniq_macs}

  uri = URI('https://rcdash.herokuapp.com/macs_seen')
  req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
  req.body = payload.to_json
  res = Net::HTTP.start(uri.hostname, uri.port) do |http|
    http.request(req)
  end

  sleep 45
end